# Changes here will be overwritten by Copier
AnswerStrategy: minimum
Authors: Mikhail Mikhasenko <mikhail.mikhasenko@cern.ch>
Indentation: 4
JuliaMinVersion: '1.6'
License: MIT
LicenseCopyrightHolders: MIT
PackageName: AlgebraPDF
PackageOwner: mmikhasenko
PackageUUID: af31816c-e40c-5333-9764-cbab4873f59c
_commit: v0.10.1
_src_path: https://github.com/abelsiqueira/BestieTemplate.jl
