name: Documentation
on:
  push:
    branches:
      - main
      - dev
  pull_request:


jobs:
  documenter:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.9.3'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
          GKSwstype: 'nul' # Plots.jl issue: `qt.qpa.xcb: could not connect to display`
          # https://discourse.julialang.org/t/failed-build-of-documentation-on-ci-due-to-missing-qt-plugin/71389
        run: julia --project=docs/ docs/make.jl
